Add the html2text utility function
Numigi/aeroo_reports pull request #15
Opened 2018-09-25 21:25 UTC by ddufresne

https://isidor.numigi.net/web#id=5179&view_type=form&model=project.task&action=292&active_id=189&menu_id=200

2018-09-29 03:08 UTC, ddufresne commented
@foutoucour j'aurais besoin de ta review ici stp.

2018-10-01 07:36 UTC, foutoucour requested changes

2018-10-01 07:36 UTC, foutoucour commented on report_aeroo/tests/test_extra_functions.py
> +    def test_format_html2text(self):
@ddufresne Il faudrait rajouter le cas ou html touche la condition `html or ''`. Je pense que c'est quand html est `None` c'est ça?
Mettre le test permettrai de documenter ce cas en plus.

2018-10-01 14:19 UTC, ddufresne commented
@foutoucour done

2018-10-01 14:41 UTC, foutoucour approved these changes

2018-10-01 14:49 UTC, merged