Migration 12
Numigi/aeroo_reports pull request #19
Opened 2018-11-12 22:41 UTC by ddufresne

https://isidor.numigi.net/web?#id=5757&view_type=form&model=project.task&action=292&active_id=203&menu_id=200

2018-11-13 23:24 UTC, foutoucour requested changes

2018-11-13 23:24 UTC, foutoucour commented on report_aeroo/controllers/portal.py
> +class PortalAccountWithAerooInvoiceReport(CustomerPortal):
Pourquoi ce n'était pas necessaire dans la version 11?

2018-11-14 16:03 UTC, ddufresne commented on report_aeroo/controllers/portal.py
> +class PortalAccountWithAerooInvoiceReport(CustomerPortal):
parce qu'en v11, le code source de Odoo faisait appel à une méthode pouvant imprimer n'importe quel type de rapport.

En v12, l'éditeur a ajouté des contraintes pour vérifier que le rapport est qweb-pdf, qweb-text ou qweb-html.

2018-11-14 20:10 UTC, foutoucour approved these changes

2018-11-14 20:33 UTC, merged