Aeroo checks: fix case where credit notes are reconciled before.
Numigi/aeroo_reports pull request #23
Opened 2018-12-05 10:00 UTC by ddufresne

Fix the case where the refund is reconciled with the invoice before the payment.

@foutoucour j'ai pensé à ce problème entre temps depuis hier.

Les 4 premiers tests n'ont pas été modifiés. Je les ai juste rendu plus explicites.

2018-12-13 03:58 UTC, ddufresne commented
@foutoucour pourrais-tu réviser ce PR stp? Quentin et Julie vont en avoir besoin.

2018-12-13 20:39 UTC, foutoucour requested changes

2018-12-13 20:39 UTC, foutoucour commented on account_check_printing_aeroo/print_stub_lines.py
>              invoice_payment_reconcile = (
Salut,
Je comprends pas ce que fait cet itérateur? Est ce que tu pourrais m'expliquer ou exploser le code pour le rendre plus accessible?
En plus, je comprends pas pourquoi ça règle le bug.

Merci

2018-12-14 12:24 UTC, ddufresne commented on account_check_printing_aeroo/print_stub_lines.py
>              invoice_payment_reconcile = (
Je suis d'accord, c'est très ordinaire comme code. Je vais améliorer ça.

2018-12-14 13:20 UTC, ddufresne commented
@foutoucour done

2018-12-14 13:59 UTC, foutoucour approved these changes

2018-12-14 13:59 UTC, merged