Allow replacing a qweb report with an aeroo report
Numigi/aeroo_reports pull request #25
Opened 2019-06-27 18:20 UTC by ddufresne

https://isidor.numigi.net/web#id=12088&view_type=form&model=project.task&action=298&menu_id=200

2019-06-27 18:22 UTC, foutoucour requested changes
Je comprends pas pourquoi le travail a été fait dans ce module. Ça semble un bon candidat de faire ça dans un module séparé.
Tu peux me donner plus de contexte ?

2019-06-27 18:29 UTC, ddufresne commented
> Je comprends pas pourquoi le travail a été fait dans ce module. Ça semble un bon candidat de faire ça dans un module séparé.
> Tu peux me donner plus de contexte ?

@foutoucour en effet, ça peut être dans un module séparé. Ça améliorerait la lisibilité du code.

2019-06-27 19:14 UTC, ddufresne commented
@foutoucour done ;)

2019-08-02 15:43 UTC, ddufresne commented
@foutoucour est-ce qu'on peut merger ceci?

2019-08-02 20:14 UTC, foutoucour approved these changes

2019-08-02 20:14 UTC, merged